"use client";

import { createClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";
import { useEffect, useRef, useState } from "react";

import { API, listBoards, type Board } from "@/lib/api";

import { hlJsonHtml, JsonView, Pre, CodeBlock } from "../components/playground/hl";
import { StagePipeline, useStagePipeline } from "../components/playground/Pipeline";
import {
  Caption,
  connBadge,
  ConnectionBadge,
  MetricStat,
  PageHeader,
  Panel,
  StepList,
} from "../components/playground/ui";

import { BoardService } from "./gen/protocollab/v1/greet_pb";

const transport = createConnectTransport({ baseUrl: `${API}/rpc` });
const client = createClient(BoardService, transport);

const UNARY_STAGES = ["Typed request", "Serialize", "POST /rpc", "Server", "Typed response"];

const PROTO = `syntax = "proto3";
package protocollab.v1;

service BoardService {
  rpc GetBoardStats(BoardStatsRequest) returns (BoardStatsResponse);
  rpc WatchBoard(WatchRequest) returns (stream BoardEvent);
}

message BoardStatsResponse {
  int32 total = 1;
  int32 todo = 2;
  int32 in_progress = 3;
  int32 done = 4;
  int32 members = 5;
}
message BoardEvent {
  int64 seq = 1;
  string type = 2;
  string task_id = 3;
}`;

const GENERATED_TS = `// generated by buf → board_service_connect.ts
import { createClient } from "@connectrpc/connect";

const client = createClient(BoardService);

client.getBoardStats(req): Promise<BoardStatsResponse>;
client.watchBoard(req):   AsyncIterable<BoardEvent>;`;

type Stats = {
  total: number;
  todo: number;
  inProgress: number;
  done: number;
  members: number;
};

type WireFormat = "JSON" | "binary";

// Build a representative protobuf hex byte string from the boardId bytes:
// field 1 (board_id), wire-type 2 (length-delimited) → tag 0x0a, length, bytes.
function hex(bytes: number[]): string {
  return bytes.map((x) => (x & 0xff).toString(16).padStart(2, "0")).join(" ");
}
function pbReqHex(boardId: string): string {
  return hex([0x0a, boardId.length & 0xff, ...[...boardId].map((c) => c.charCodeAt(0) & 0xff)]);
}

export default function GrpcPage() {
  const [boards, setBoards] = useState<Board[]>([]);
  const [boardId, setBoardId] = useState<string | null>(null);

  // unary
  const [stats, setStats] = useState<Stats | null>(null);
  const [latency, setLatency] = useState<number | null>(null);
  const [jsonBytes, setJsonBytes] = useState<number | null>(null);
  const [wire, setWire] = useState<WireFormat>("JSON");
  const { stages, animate, running } = useStagePipeline(UNARY_STAGES, 330);

  // server-stream
  const [streamState, setStreamState] = useState<
    "connecting" | "open" | "closed" | "error"
  >("closed");
  const [frames, setFrames] = useState<{ seq: string; type: string; taskId: string }[]>([]);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => {
    listBoards().then((b) => {
      setBoards(b);
      setBoardId(b[0]?.id ?? null);
    });
    return () => abortRef.current?.abort();
  }, []);

  const hasBoards = boards.length > 0;

  async function callUnary() {
    if (running || !boardId) return;
    setStats(null);
    setLatency(null);
    setJsonBytes(null);
    const t0 = performance.now();
    try {
      const res = await client.getBoardStats({ boardId });
      const s: Stats = {
        total: res.total,
        todo: res.todo,
        inProgress: res.inProgress,
        done: res.done,
        members: res.members,
      };
      await animate("done");
      setLatency(Math.round(performance.now() - t0));
      setJsonBytes(JSON.stringify(s).length);
      setStats(s);
    } catch (e) {
      await animate("error");
      setLatency(Math.round(performance.now() - t0));
      setStats(null);
      setJsonBytes(null);
      console.error(e);
    }
  }

  async function startStream() {
    if (!boardId || streamState === "open" || streamState === "connecting") return;
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setFrames([]);
    setStreamState("connecting");
    try {
      let first = true;
      for await (const ev of client.watchBoard({ boardId }, { signal: controller.signal })) {
        if (first) {
          setStreamState("open");
          first = false;
        }
        const fr = { seq: String(ev.seq), type: ev.type, taskId: ev.taskId };
        setFrames((prev) => [fr, ...prev].slice(0, 8));
      }
      // stream ended on its own
      if (!controller.signal.aborted) setStreamState("closed");
    } catch (e) {
      if (controller.signal.aborted || (e as Error)?.name === "AbortError") {
        setStreamState("closed");
      } else {
        setStreamState("error");
        console.error(e);
      }
    }
  }

  function stopStream() {
    abortRef.current?.abort();
    abortRef.current = null;
    setStreamState("closed");
  }

  const shownBytes =
    jsonBytes == null
      ? "—"
      : wire === "binary"
        ? Math.max(8, Math.round(jsonBytes * 0.34))
        : jsonBytes;

  // request frame HTML (header lines + JSON body or protobuf hex)
  const reqPath =
    "<span style=\"color:#4ade80;font-weight:700\">POST</span> " +
    "<span style=\"color:#d7e0ee\">/protocollab.v1.BoardService/GetBoardStats</span>";
  const verHdr =
    "<span style=\"color:#8595ab\">connect-protocol-version</span>: <span style=\"color:#38bdf8\">1</span>";
  let reqHtml: string;
  if (wire === "binary" && boardId) {
    const h = pbReqHex(boardId);
    reqHtml =
      reqPath +
      "\n<span style=\"color:#8595ab\">content-type</span>: <span style=\"color:#38bdf8\">application/proto</span>\n" +
      verHdr +
      "\n\n<span style=\"color:#3f4d63\"># BoardStatsRequest · protobuf (" +
      h.split(" ").length +
      " bytes)</span>\n<span style=\"color:#fbbf24;word-break:break-all\">" +
      h +
      "</span>";
  } else {
    reqHtml =
      reqPath +
      "\n<span style=\"color:#8595ab\">content-type</span>: <span style=\"color:#38bdf8\">application/json</span>\n" +
      verHdr +
      "\n\n" +
      hlJsonHtml({ boardId: boardId ?? "" });
  }

  const wireNote =
    wire === "binary"
      ? "binary protobuf: about 3× smaller on the wire than JSON"
      : "JSON: human-readable. Toggle to binary protobuf to shrink it.";

  const wireBtn = (active: boolean): React.CSSProperties => ({
    fontFamily: "inherit",
    fontSize: 11,
    padding: "5px 11px",
    borderRadius: 6,
    cursor: "pointer",
    border: `1px solid ${active ? "#4ade80" : "#202c3e"}`,
    background: "transparent",
    color: active ? "#4ade80" : "#8595ab",
  });

  const streaming = streamState === "open" || streamState === "connecting";
  const badge = connBadge(streamState, "streaming");

  return (
    <div>
      <PageHeader
        command="grpc"
        flag="--via connect"
        subtitle="A typed Protobuf contract, generated into a Python server and a TypeScript client by buf. The browser calls it directly over Connect, with no proxy."
      />
      <StepList
        minCol={210}
        steps={[
          <>
            Read the <span style={{ color: "#4ade80" }}>.proto</span> contract.
          </>,
          <>
            Run a <span style={{ color: "#4ade80" }}>unary</span> call, then watch it serialize →
            POST → resolve.
          </>,
          <>
            Start a <span style={{ color: "#4ade80" }}>server-stream</span> and watch typed frames
            arrive.
          </>,
          <>
            Open DevTools → <strong>Network</strong> to see a readable POST.
          </>,
        ]}
      />

      {/* the contract */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "minmax(0,1fr) minmax(0,1fr)",
          gap: 16,
          marginBottom: 16,
          alignItems: "start",
        }}
      >
        <Panel>
          <div style={{ display: "flex", alignItems: "center", marginBottom: 11 }}>
            <div style={{ color: "#8595ab", fontSize: 11, flex: 1 }}>// the contract</div>
            <span
              style={{
                color: "#3f4d63",
                fontSize: 10,
                border: "1px solid #202c3e",
                padding: "2px 7px",
                borderRadius: 5,
              }}
            >
              proto3
            </span>
          </div>
          <CodeBlock code={PROTO} style={{ fontSize: 11.5, lineHeight: 1.55 }} />
        </Panel>

        <Panel>
          <div style={{ display: "flex", alignItems: "center", marginBottom: 11 }}>
            <div style={{ color: "#8595ab", fontSize: 11, flex: 1 }}>// generated client</div>
            <span
              style={{
                color: "#3f4d63",
                fontSize: 10,
                border: "1px solid #202c3e",
                padding: "2px 7px",
                borderRadius: 5,
              }}
            >
              typescript
            </span>
          </div>
          <CodeBlock code={GENERATED_TS} style={{ fontSize: 11.5, lineHeight: 1.55 }} />
          <Caption style={{ marginTop: 11, marginBottom: 0, color: "#3f4d63", lineHeight: 1.5 }}>
            proto → types: the same contract drives the server and this client.
          </Caption>
        </Panel>
      </div>

      {/* unary */}
      <Panel style={{ padding: "20px 22px", marginBottom: 16 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: 18,
            flexWrap: "wrap",
          }}
        >
          <div style={{ color: "#8595ab", fontSize: 11 }}>// unary · GetBoardStats</div>
          <div style={{ flex: 1 }} />
          <div style={{ display: "flex", gap: 7 }}>
            {boards.map((b) => {
              const active = b.id === boardId;
              return (
                <button
                  key={b.id}
                  onClick={() => {
                    setBoardId(b.id);
                    setStats(null);
                    setLatency(null);
                    setJsonBytes(null);
                  }}
                  style={{
                    fontFamily: "inherit",
                    fontSize: 12,
                    padding: "7px 13px",
                    borderRadius: 7,
                    cursor: "pointer",
                    border: `1px solid ${active ? "#38bdf8" : "#202c3e"}`,
                    background: active ? "rgba(56,189,248,.08)" : "transparent",
                    color: active ? "#38bdf8" : "#8595ab",
                  }}
                >
                  {b.name}
                </button>
              );
            })}
          </div>
          <button
            onClick={callUnary}
            disabled={running || !hasBoards}
            style={{
              background: "rgba(74,222,128,.10)",
              border: "1px solid #4ade80",
              color: "#4ade80",
              fontFamily: "inherit",
              fontSize: 12.5,
              fontWeight: 700,
              padding: "9px 16px",
              borderRadius: 8,
              cursor: running || !hasBoards ? "default" : "pointer",
              opacity: running || !hasBoards ? 0.6 : 1,
            }}
          >
            {running ? "calling…" : "▸ call BoardService.getBoardStats()"}
          </button>
        </div>

        <div style={{ maxWidth: 720, margin: "0 auto 22px" }}>
          <StagePipeline stages={stages} maxWidth={720} />
        </div>

        <div
          style={{
            display: "grid",
            gridTemplateColumns: "minmax(0,1fr) 240px",
            gap: 16,
            alignItems: "start",
            borderTop: "1px dashed #202c3e",
            paddingTop: 18,
          }}
        >
          <div style={{ minWidth: 0 }}>
            <div style={{ color: "#4ade80", fontSize: 10, marginBottom: 6 }}>
              → sent · request frame
            </div>
            <Pre
              html={reqHtml}
              style={{
                margin: "0 0 14px",
                padding: 12,
                background: "#0d131d",
                border: "1px solid #202c3e",
                borderRadius: 8,
                fontSize: 11.5,
                lineHeight: 1.55,
              }}
            />
            <div style={{ color: "#38bdf8", fontSize: 10, marginBottom: 6 }}>
              ← received · BoardStatsResponse (decoded)
            </div>
            {stats ? (
              <JsonView value={stats} maxHeight={220} style={{ padding: 12 }} />
            ) : (
              <Pre
                html={'<span style="color:#3f4d63">// call the RPC to see the typed response</span>'}
                style={{
                  margin: 0,
                  padding: 12,
                  background: "#0d131d",
                  border: "1px solid #202c3e",
                  borderRadius: 8,
                  fontSize: 12,
                }}
              />
            )}
          </div>

          <div>
            <div style={{ display: "flex", gap: 10, marginBottom: 12 }}>
              <MetricStat value={latency != null ? latency : "—"} label="LATENCY MS" big={19} />
              <MetricStat
                value={shownBytes}
                label="PAYLOAD BYTES"
                color="#4ade80"
                big={19}
              />
            </div>
            <div style={{ color: "#3f4d63", fontSize: 10, marginBottom: 6 }}>wire format</div>
            <div style={{ display: "flex", gap: 7, marginBottom: 8 }}>
              <button onClick={() => setWire("JSON")} style={wireBtn(wire === "JSON")}>
                JSON
              </button>
              <button onClick={() => setWire("binary")} style={wireBtn(wire === "binary")}>
                binary protobuf
              </button>
            </div>
            <div style={{ color: "#8595ab", fontSize: 10.5, lineHeight: 1.5 }}>{wireNote}</div>
          </div>
        </div>
      </Panel>

      {/* server stream */}
      <Panel style={{ padding: "20px 22px", marginBottom: 16 }}>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: 12,
            marginBottom: 16,
            flexWrap: "wrap",
          }}
        >
          <div style={{ color: "#8595ab", fontSize: 11 }}>// server-stream · WatchBoard</div>
          <ConnectionBadge label={badge.label} color={badge.color} pulse={badge.pulse} />
          <div style={{ flex: 1 }} />
          <button
            onClick={startStream}
            disabled={streaming || !hasBoards}
            style={{
              background: streaming || !hasBoards ? "#0d131d" : "rgba(74,222,128,.10)",
              border: `1px solid ${streaming || !hasBoards ? "#202c3e" : "#4ade80"}`,
              color: streaming || !hasBoards ? "#3f4d63" : "#4ade80",
              fontFamily: "inherit",
              fontSize: 12,
              fontWeight: 700,
              padding: "8px 15px",
              borderRadius: 8,
              cursor: streaming || !hasBoards ? "default" : "pointer",
            }}
          >
            ▸ Start stream
          </button>
          <button
            onClick={stopStream}
            disabled={!streaming}
            style={{
              background: "transparent",
              border: `1px solid ${streaming ? "#f87171" : "#202c3e"}`,
              color: streaming ? "#f87171" : "#3f4d63",
              fontFamily: "inherit",
              fontSize: 12,
              padding: "8px 15px",
              borderRadius: 8,
              cursor: streaming ? "pointer" : "default",
            }}
          >
            ■ Stop
          </button>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 8, minHeight: 160 }}>
          {frames.length > 0 ? (
            frames.map((f, i) => {
              const len = 14 + f.type.length;
              const env =
                "00 " + hex([(len >> 24) & 255, (len >> 16) & 255, (len >> 8) & 255, len & 255]);
              return (
                <div
                  key={`${f.seq}-${i}`}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: 14,
                    background: "#0d131d",
                    border: "1px solid #202c3e",
                    borderRadius: 9,
                    padding: "10px 14px",
                    animation: "pl-slidein .3s ease",
                  }}
                >
                  <span
                    style={{ color: "#3f4d63", fontSize: 10, flex: "none", fontFamily: "inherit" }}
                    title="envelope: 1 flag byte + 4-byte big-endian length"
                  >
                    {env}
                  </span>
                  <span
                    style={{ color: "#fbbf24", fontSize: 13, fontWeight: 700, flex: "none" }}
                  >
                    {f.seq.padStart(2, "0")}
                  </span>
                  <span style={{ color: "#38bdf8", fontSize: 12.5, fontWeight: 700, flex: 1 }}>
                    BoardEvent · {f.type}
                  </span>
                  <span style={{ color: "#8595ab", fontSize: 11 }}>task_id: {f.taskId}</span>
                </div>
              );
            })
          ) : (
            <div
              style={{
                flex: 1,
                minHeight: 160,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                color: "#3f4d63",
                fontSize: 12,
              }}
            >
              // start the stream to watch typed BoardEvent frames arrive
            </div>
          )}
        </div>
        <div style={{ color: "#3f4d63", fontSize: 10.5, marginTop: 12, lineHeight: 1.5 }}>
          Frames arrive when tasks change on that board — generate a task on the Real-time page or
          via REST. These are real BoardEvents from the server&apos;s EventBus.
        </div>
      </Panel>

      {!hasBoards && (
        <div
          style={{
            color: "#fbbf24",
            fontSize: 11,
            marginBottom: 16,
            lineHeight: 1.5,
          }}
        >
          No board yet — sign in &amp; click &ldquo;Create sample data&rdquo; on Home to enable the
          unary call and the stream.
        </div>
      )}

      <div
        style={{
          background: "#0d131d",
          border: "1px solid #202c3e",
          borderRadius: 10,
          padding: "14px 18px",
          color: "#8595ab",
          fontSize: 12.5,
          lineHeight: 1.6,
        }}
      >
        Same contract, two call styles: <span style={{ color: "#4ade80" }}>unary</span> and{" "}
        <span style={{ color: "#4ade80" }}>server-streaming</span>, both native in the browser, with
        no Envoy or grpc-web proxy.
      </div>
    </div>
  );
}
